version: '3.8'

services:
  postgres:
    container_name: postgres_busmanage
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bertoh
      POSTGRES_PASSWORD: jesus114
      POSTGRES_DB: busmanage
    ports:
      - '5432:5432'

  pdadmin:
    container_name: pgadmin_busmanage
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
